places=['noronha','roma','eua','israel','japao','europe','canada']
print("\nLista Python pura:")
print(places)
print("\nLista em ordem alfabetica com sorted():")
print(sorted(places))
print("\nLista original:")
print(places)
print("\nLista em ordem alfabetica reversa com sorted() reverse=True:")
print(sorted(places,reverse=True))
print("\nLista original:")
print(places)
places.reverse()
print("\nUsando reverse():")
print(places)
places.reverse()
print("\nUsando reverse() novamente:")
print(places)
places.sort()
print("\nOrdenando com sort():")
print(places)
print("\nOrdenando com sort(reverse=True)")
places.sort(reverse=True)
print(places)
